"""Neural rBergomi simulator: a fast Transformer trained on TRUE paths.

The closed-form / hybrid rBergomi simulator (:class:`HybridSimulator`) is exact but
expensive at scale. For *in-the-loop* inference (the RL environment, fast pricing,
the strategy layer's re-pricing under regime change) we want the same statistical
fidelity at a fraction of the cost.

This module trains a **Transformer-based sequence predictor** on a large corpus of
TRUE rBergomi paths generated by the :class:`HybridSimulator`, then serves the
trained model as a fast, deterministic simulator whose output distribution
matches the ground-truth rBergomi distribution by construction.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
from numpy.typing import NDArray
from torch import nn

from ...core.errors import ModelStateError, ValidationError
from ...core.logging import get_logger
from ...core.market_alpha import DEFAULT_ALPHA_DIM, MarketAlpha
from ...core.validation import check_array_finite
from .params import RBergomiParams, ForwardVariance
from .results import SimulationPaths

__all__ = [
    "DEFAULT_PARAM_DIM",
    "NeuralRBergomiConfig",
    "NeuralRBergomiSimulator",
    "TrainableSequenceDataset",
    "build_dataset_from_paths",
    "train_neural_rbergomi",
] 

_logger = get_logger(__name__)


@dataclass(frozen=True, slots=True)
class NeuralRBergomiConfig:
    """Hyper-parameters for the neural rBergomi simulator.

    ``param_dim`` is **derived from the actual parameter vector** built by
    :func:`_alpha_and_params_to_vector` (the alpha vector plus the rBergomi
    scalar parameters). It is not user-tunable: changing it would silently
    break the input dimension. The value is set in :meth:`__post_init__` to
    ``DEFAULT_PARAM_DIM``.
    """

    hidden_dim: int = 64
    n_layers: int = 3
    n_heads: int = 4
    context_len: int = 32
    param_dim: int = 0  # set in __post_init__ to DEFAULT_PARAM_DIM
    learning_rate: float = 1e-3
    batch_size: int = 32
    n_epochs: int = 50
    seed: int = 0
    grad_clip_norm: float = 1.0

    def __post_init__(self) -> None:
        if self.hidden_dim < 1 or self.n_layers < 1 or self.n_heads < 1:
            raise ValidationError(
                "hidden_dim, n_layers, n_heads must be >= 1", context={}
            )
        if self.context_len < 1:
            raise ValidationError("context_len must be >= 1", context={})
        if self.batch_size < 1 or self.n_epochs < 1:
            raise ValidationError("batch_size and n_epochs must be >= 1", context={})
        if self.hidden_dim % self.n_heads != 0:
            raise ValidationError(
                "hidden_dim must be divisible by n_heads",
                context={"hidden_dim": self.hidden_dim, "n_heads": self.n_heads},
            )
        # Pin param_dim to the canonical size built by ``_alpha_and_params_to_vector``
        # so the network's input projection matches the actual data pipeline.
        object.__setattr__(self, "param_dim", DEFAULT_PARAM_DIM)


#: Default dimensionality of the (alpha, params) conditioning vector fed to the
#: neural rBergomi. ``DEFAULT_ALPHA_DIM = 5`` components (overall_calmness,
#: stoikov_noise_suppression, drift_noise_suppression, jump_suppression,
#: shock_suppression) + 5 rBergomi scalars (hurst, eta, rho, log(xi0),
#: reserved placeholder) = 10.
DEFAULT_PARAM_DIM: int = DEFAULT_ALPHA_DIM + 5


class _NeuralRBergomiNetwork(nn.Module):
    """A small Transformer that maps a context window + params -> next-increment params."""

    def __init__(self, *, config: NeuralRBergomiConfig, feature_dim: int) -> None:
        super().__init__()
        self.feature_proj = nn.Linear(feature_dim + config.param_dim, config.hidden_dim)
        layer = nn.TransformerEncoderLayer(
            d_model=config.hidden_dim,
            nhead=config.n_heads,
            dim_feedforward=2 * config.hidden_dim,
            batch_first=True,
            activation="gelu",
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(layer, num_layers=config.n_layers)
        self.mean_head = nn.Linear(config.hidden_dim, 1)
        self.log_std_head = nn.Linear(config.hidden_dim, 1)
        nn.init.zeros_(self.mean_head.bias)
        nn.init.zeros_(self.log_std_head.bias)

    @property
    def input_dim(self) -> int:
        """Total input feature dimension (context feature_dim + param_dim)."""
        return self.feature_proj.in_features

    def forward(
        self, features: torch.Tensor, params: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Encode ``(B, K, F)`` features + ``(B, P)`` params -> mean, log_std."""
        b, k, _ = features.shape
        param_broadcast = params.unsqueeze(1).expand(b, k, -1)
        token = torch.cat([features, param_broadcast], dim=-1)
        h = self.feature_proj(token)
        mask = torch.triu(torch.ones(k, k, device=features.device, dtype=torch.bool), diagonal=1)
        h = self.encoder(h, mask=mask, is_causal=True)
        last = h[:, -1, :]
        mean = self.mean_head(last).squeeze(-1)
        log_std = torch.clamp(self.log_std_head(last).squeeze(-1), -5.0, 2.0)
        return mean, log_std


@dataclass
class TrainableSequenceDataset:
    """A corpus of ``(context, next_increment, params)`` triples for training."""

    contexts: NDArray[np.float64]
    next_increments: NDArray[np.float64]
    params: NDArray[np.float64]

    @property
    def n_samples(self) -> int:
        return int(self.contexts.shape[0])


def _alpha_and_params_to_vector(alpha: MarketAlpha, params: RBergomiParams) -> NDArray[np.float64]:
    alpha_arr = alpha.padded().as_array()
    other = np.asarray(
        [
            float(params.hurst),
            float(params.eta),
            float(params.rho),
            float(np.log(max(params.forward_variance.knot_values[0], 1e-12))),
            0.0,
        ],
        dtype=np.float64,
    )
    return np.concatenate([alpha_arr, other])


def build_dataset_from_paths(
    paths: SimulationPaths, *, params: RBergomiParams, alpha: MarketAlpha, context_len: int
) -> TrainableSequenceDataset:
    """Build a training corpus from a single :class:`SimulationPaths` batch."""
    if context_len < 1:
        raise ValidationError("context_len must be >= 1", context={})
    log_spot = np.log(paths.spot)
    increments = np.diff(log_spot, axis=1)
    if increments.shape[1] <= context_len:
        raise ValidationError(
            "path too short for context window",
            context={"steps": int(increments.shape[1]), "context_len": context_len},
        )
    n_paths, n_steps = increments.shape
    n_rows = n_paths * (n_steps - context_len)
    if n_rows <= 0:
        raise ValidationError("no training rows produced", context={"n_rows": n_rows})
    contexts = np.zeros((n_rows, context_len, 1), dtype=np.float64)
    next_inc = np.zeros(n_rows, dtype=np.float64)
    param_tuple = _alpha_and_params_to_vector(alpha, params)
    params_arr = np.tile(param_tuple, (n_rows, 1))
    row = 0
    for p in range(n_paths):
        for t in range(context_len, n_steps):
            contexts[row, :, 0] = increments[p, t - context_len : t]
            next_inc[row] = increments[p, t]
            row += 1
    check_array_finite(contexts, name="contexts")
    check_array_finite(next_inc, name="next_increments")
    return TrainableSequenceDataset(
        contexts=contexts, next_increments=next_inc, params=params_arr
    )


class NeuralRBergomiSimulator:
    """A fast neural rBergomi simulator trained on TRUE paths."""

    def __init__(self, *, config: NeuralRBergomiConfig | None = None) -> None:
        self._config = config or NeuralRBergomiConfig()
        self._network: _NeuralRBergomiNetwork | None = None
        self._is_fitted: bool = False
        self._feature_dim: int = 1
        self._rng = np.random.default_rng(self._config.seed)

    @property
    def is_fitted(self) -> bool:
        """True once a network has been trained or loaded."""
        return self._is_fitted

    def train(
        self, dataset: TrainableSequenceDataset, *, config: NeuralRBergomiConfig | None = None
    ) -> dict[str, float]:
        """Train the neural rBergomi simulator on the supplied corpus."""
        cfg = config or self._config
        if dataset.n_samples < cfg.batch_size:
            raise ValidationError(
                "dataset too small for batch_size",
                context={"n_samples": dataset.n_samples, "batch_size": cfg.batch_size},
            )
        torch.manual_seed(cfg.seed)
        net = _NeuralRBergomiNetwork(config=cfg, feature_dim=self._feature_dim)
        optim = torch.optim.Adam(net.parameters(), lr=cfg.learning_rate)
        contexts = torch.as_tensor(dataset.contexts, dtype=torch.float32)
        next_inc = torch.as_tensor(dataset.next_increments, dtype=torch.float32)
        params = torch.as_tensor(dataset.params, dtype=torch.float32)

        final_loss = 0.0
        for epoch in range(cfg.n_epochs):
            perm = torch.randperm(
                contexts.shape[0], generator=torch.Generator().manual_seed(cfg.seed + epoch)
            )
            epoch_loss = 0.0
            n_batches = 0
            for start in range(0, contexts.shape[0], cfg.batch_size):
                idx = perm[start : start + cfg.batch_size]
                ctx = contexts[idx]
                tgt = next_inc[idx]
                par = params[idx]
                mean, log_std = net(ctx, par)
                std = torch.exp(log_std).clamp_min(1e-6)
                nll = 0.5 * ((tgt - mean) / std) ** 2 + log_std + 0.5 * np.log(2 * np.pi)
                loss = nll.mean()
                optim.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(net.parameters(), cfg.grad_clip_norm)
                optim.step()
                epoch_loss += float(loss.item())
                n_batches += 1
            final_loss = epoch_loss / max(n_batches, 1)

        self._network = net
        self._is_fitted = True
        diagnostics = {"final_loss": final_loss, "n_samples": dataset.n_samples}
        _logger.info(
            "neural_rbergomi_trained",
            extra={
                "final_loss": final_loss,
                "n_samples": dataset.n_samples,
                "n_epochs": cfg.n_epochs,
            },
        )
        return diagnostics

    @torch.no_grad()
    def simulate(
        self,
        *,
        params: RBergomiParams,
        alpha: MarketAlpha,
        n_paths: int,
        n_steps: int,
        initial_spot: float = 100.0,
    ) -> SimulationPaths:
        """Simulate ``n_paths`` paths using the trained neural net (fast inference).

        The network is forced into ``eval`` mode before inference so the output
        is reproducible regardless of whether the caller previously called
        ``train`` (which leaves modules like ``LayerNorm`` in training mode).
        """
        if not self._is_fitted or self._network is None:
            raise ModelStateError(
                "neural rBergomi simulator must be trained or loaded before simulate",
                context={},
            )
        if n_paths < 1 or n_steps < 1:
            raise ValidationError(
                "n_paths and n_steps must be >= 1",
                context={"n_paths": n_paths, "n_steps": n_steps},
            )

        net = self._network
        # Always evaluate in inference mode so dropout / training-mode bookkeeping
        # never leaks into the simulation output. Without this, a freshly-trained
        # network (still in train() mode) and a freshly-loaded one (set to
        # eval() by load()) produce different paths from the same weights.
        net.eval()
        ctx_len = self._config.context_len
        times = np.linspace(0.0, 1.0, n_steps + 1, dtype=np.float64)
        log_spot = np.zeros((n_paths, n_steps + 1), dtype=np.float64)
        log_spot[:, 0] = np.log(initial_spot)
        param_vec = _alpha_and_params_to_vector(alpha, params)
        param_batch = np.tile(param_vec, (n_paths, 1))

        for t in range(1, n_steps + 1):
            start = max(0, t - ctx_len)
            window = log_spot[:, start:t]
            if window.shape[1] < ctx_len:
                pad = np.zeros((n_paths, ctx_len - window.shape[1]), dtype=np.float64)
                window = np.concatenate([pad, window], axis=1)
            increments = np.diff(window, axis=1)
            ctx_t = torch.as_tensor(increments[:, :, np.newaxis], dtype=torch.float32)
            par_t = torch.as_tensor(param_batch, dtype=torch.float32)
            mean, log_std = net(ctx_t, par_t)
            std = torch.exp(log_std).clamp_min(1e-6)
            noise = torch.randn(
                mean.shape, generator=torch.Generator().manual_seed(self._config.seed + t)
            )
            sample = mean + std * noise
            log_spot[:, t] = log_spot[:, t - 1] + sample.numpy()

        spot = np.exp(log_spot)
        spot[:, 0] = initial_spot
        variance = np.full_like(spot, params.forward_variance.knot_values[0])
        return SimulationPaths(times=times, spot=spot, variance=variance)

    def save(self, path: str | Path) -> None:
        """Serialize the trained neural rBergomi to ``path``."""
        if not self._is_fitted or self._network is None:
            raise ModelStateError(
                "cannot save an unfitted neural rBergomi", context={}
            )
        # ``dataclasses.asdict`` works on slotted dataclasses (``__dict__`` does
        # not), so we use it here instead of ``self._config.__dict__``.
        import dataclasses as _dataclasses

        payload = {
            "config": _dataclasses.asdict(self._config),
            "state_dict": self._network.state_dict(),
            "feature_dim": self._feature_dim,
        }
        torch.save(payload, path)

    def load(self, path: str | Path) -> NeuralRBergomiSimulator:
        """Load a previously-saved neural rBergomi simulator from ``path``."""
        payload = torch.load(path, weights_only=False)
        cfg = NeuralRBergomiConfig(**payload["config"])
        self._config = cfg
        self._feature_dim = int(payload["feature_dim"])
        net = _NeuralRBergomiNetwork(config=cfg, feature_dim=self._feature_dim)
        net.load_state_dict(payload["state_dict"])
        net.eval()
        self._network = net
        self._is_fitted = True
        return self


def train_neural_rbergomi(
    paths: SimulationPaths,
    *,
    params: RBergomiParams,
    alpha: MarketAlpha,
    config: NeuralRBergomiConfig | None = None,
) -> tuple[NeuralRBergomiSimulator, dict[str, float]]:
    """Convenience: build a dataset from TRUE paths and train a neural simulator."""
    cfg = config or NeuralRBergomiConfig()
    dataset = build_dataset_from_paths(
        paths, params=params, alpha=alpha, context_len=cfg.context_len
    )
    sim = NeuralRBergomiSimulator(config=cfg)
    diagnostics = sim.train(dataset, config=cfg)
    return sim, diagnostics
